#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Boulder-Simple
version:      0.01
version_from: lib/Boulder/Simple.pm
installdirs:  site
requires:
    CGI::Util:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
